server:
  port: 8080

spring:
  application:
    name: gas-payer-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Blockchain configuration
blockchain:
  rpc:
    url: ${BLOCKCHAIN_RPC_URL:https://api.avax-test.network/ext/bc/C/rpc}
  chain:
    id: ${BLOCKCHAIN_CHAIN_ID:43113}
  relayer:
    gas-payer-contract-address: ${GAS_PAYER_CONTRACT_ADDRESS:}
  gas:
    price-multiplier: ${GAS_PRICE_MULTIPLIER:1.2}
    max-gas-limit: ${MAX_GAS_LIMIT:500000}
    max-gas-cost-wei: ${MAX_GAS_COST_WEI:1000000000000000000}
    max-gas-price-multiplier: ${MAX_GAS_PRICE_MULTIPLIER:3.2}

# Security configuration file path
security:
  config-path: ${SECURITY_CONFIG_FILE:/app/config/security-config.json}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

# Logging
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    com.gaspayer: ${LOGGING_LEVEL:INFO}
    com.utility.chainservice: ${LOGGING_LEVEL:INFO}
    org.web3j: WARN
    org.apache.coyote.http11.Http11Processor: ERROR
    org.apache.tomcat: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"